SistemaDeContatos/Controllers/AlterarSenhaController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaDeContatos.Filters;
using SistemaDeContatos.Helper;
using SistemaDeContatos.Models.Entities;
using SistemaDeContatos.Models.ViewModels;
using SistemaDeContatos.Services;

namespace SistemaDeContatos.Controllers
{
    [PaginaParaUsuarioLogado]
    public class AlterarSenhaController : Controller
    {
        private readonly UsuarioService _usuarioService;
        private readonly ISessao _sessao;
        public AlterarSenhaController(UsuarioService usuarioService, ISessao sessao)
        {
            _usuarioService = usuarioService;
            _sessao = sessao;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Alterar(AlterSenhaViewModel alterarSenhaModel)
        {
            try
            {
              Usuario usuarioSessao =  _sessao.BuscarSessao();
                alterarSenhaModel.Id = usuarioSessao.Id; 
                if (ModelState.IsValid)
                {
                    _usuarioService.AlterarSenha(alterarSenhaModel);
                    TempData["alertSucess"] = "Senha atualizada com sucesso";
                    return View("Index", alterarSenhaModel);
                }
                return View("Index", alterarSenhaModel);
            }
            catch(Exception e)
            {
                TempData["alertError"] = e.Message;
                return View("Index", alterarSenhaModel);
            }
           
        }
    }
}

SistemaDeContatos/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaDeContatos.Data;
using SistemaDeContatos.Helper;
using SistemaDeContatos.Models.ViewModels;
using SistemaDeContatos.Services;

namespace SistemaDeContatos.Controllers
{
    public class LoginController : Controller
    {
        private readonly UsuarioService _usuarioService;
        private readonly ISessao _sessao;
        private readonly IEmail _email;

        public LoginController(UsuarioService usuarioService, ISessao sessao, IEmail email)
        {
            _usuarioService = usuarioService;
            _sessao = sessao;
            _email = email;
        }
        public IActionResult Index()
        {
            if(_sessao.BuscarSessao() != null) return RedirectToAction(nameof(Index), "Home");
            return View();
        }

        [HttpPost]
        public IActionResult Logar(LoginViewModel loginView)
        {
            if (ModelState.IsValid)
            {
                var obj = _usuarioService.FindByLogin(loginView.Login);
                if (obj != null)
                {
                    if (obj.ValidaSenha(loginView.Senha))
                    {
                        _sessao.CriarSessao(obj);   
                        return RedirectToAction(nameof(Index), "Home");
                    }
                    TempData["alertError"] = "senha do usuário está incorreto";
                    return View("Index");
                }
                TempData["alertError"] = "Login e/ou senha do usuário está incorreto";
                return View("Index");
            }
            TempData["alertError"] = "Login e/ou senha do usuário está incorreto";
            return View("Index");
        }

        public IActionResult Redefinir()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Redefinir(RedefinirSenhaViewModel redefinir)
        {
            if (ModelState.IsValid)
            {
              var usuario =  _usuarioService.FindByLoginEmail(redefinir.Login, redefinir.Email);
              if(usuario != null)
                {
                    string novaSenha = usuario.GerarNovaSenha();
                    string mensagem = $"Sua nova senha é {novaSenha}";
                    bool enviado = _email.Enviar(usuario.Email, "Sistema de contatos - Nova Senha",mensagem);
                    if (enviado)
                    {
                        _usuarioService.Update(usuario);
                        TempData["alertSucess"] = "Senha redefinida com sucesso!";
                    }
                    else
                    {
                        TempData["alertError"] = "Não foi possível enviar o email, tente novamente";
                    }
                    
                    return RedirectToAction(nameof(Index));
                }
                TempData["alertError"] = "Usuário ou email não encontrados!";
                return View();
            }
            TempData["alertError"] = "Usuário ou email não encontrados!";
            return View();
        }
       
        public IActionResult Logout()
        {
            _sessao.RemoverSessao();
            return RedirectToAction(nameof(Index));
        }
    }
}

SistemaDeContatos/Views/AlterarSenha/Index.cshtml
@model SistemaDeContatos.Models.ViewModels.AlterSenhaViewModel;

@{
    ViewData["title"] = "Alterar senha";
}

<h1 class="text-sm-center">@ViewData["title"]</h1>

@if (TempData["alertError"] != null)
{
    <div class="alert alert-danger" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
        @TempData["alertError"];
    </div>
}

@if (TempData["alertSucess"] != null)
{
    <div class="alert alert-success" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
        @TempData["alertSucess"];
    </div>
}

<div >
    <div class="row align-content-md-center">
        <form asp-action="Alterar" asp-controller="AlterarSenha">
            
            <div class="form-group">
                <label for"SenhaAtual" class="form-label">Senha Atual</label>
                <input type="password" asp-for="SenhaAtual"/>
                <span class="text-danger" asp-validation-for="SenhaAtual"></span>
            </div>
            <div class="form-group">
                <label for"SenhaAtual" class="form-label">Nova Senha</label>
                <input type="password" asp-for="NovaSenha" />
                <span class="text-danger" asp-validation-for="NovaSenha"></span>
            </div>
            <div class="form-group">
                <label for"SenhaAtual" class="form-label">Confirmar Senha</label>
                <input type="password" asp-for="ConfirmarNovaSenha" />
                <span class="text-danger" asp-validation-for="ConfirmarNovaSenha"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success">Alterar</button>
                <a role="button" class="btn btn-danger" asp-action="Index" asp-controller="Login">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }