SistemaDeContatos/Models/Entities/Contato.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Reflection.Metadata.Ecma335;

namespace SistemaDeContatos.Models.Entities
{
    public class Contato
    {
        public int Id { get; set; }

        [Display(Name ="Nome")]
        [Required(ErrorMessage ="Digite um nome")]
        [StringLength(maximumLength:100, MinimumLength =3,ErrorMessage ="digite um nome válido")]
        public string Nome { get; set; }

        [Display(Name = "Email")]
        [Required(ErrorMessage = "Digite um Email")]
        [EmailAddress(ErrorMessage ="Digite um email válido")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Display(Name = "Celular")]
        [Required(ErrorMessage = "Digite um Numero")]
        [StringLength(9, ErrorMessage = "digite um nome válido")]
        public string Celular { get; set; }
        
        public int? UsuarioId { get; set; }
        public Usuario? Usuario { get; set; }

       

        public Contato()
        {

        }

        public Contato(string nome, string email, string celular)
        {
            Nome = nome;
            Email = email;
            Celular = celular;

        }
    }
}

SistemaDeContatos/Controllers/ContatosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Server.IIS.Core;
using SistemaDeContatos.Filters;
using SistemaDeContatos.Helper;
using SistemaDeContatos.Models.Entities;
using SistemaDeContatos.Services;

namespace SistemaDeContatos.Controllers
{
    [PaginaParaUsuarioLogado]
    public class ContatosController : Controller
    {
        private readonly ContatoService _contatosService;
        private readonly ISessao _sessao;
        public ContatosController(ContatoService contatoService, ISessao sessao)
        {
            _contatosService = contatoService;
            _sessao = sessao;
        }

        public IActionResult Index()
        {
            var usuarioSessao = _sessao.BuscarSessao();
            var contatos = _contatosService.FindAll(usuarioSessao.Id);
            return View(contatos);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Contato contato)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var usuarioSessao = _sessao.BuscarSessao();
                    contato.UsuarioId = usuarioSessao.Id;

                    _contatosService.AddContato(contato);
                    TempData["alertSucess"] = "Contato Cadastrado com sucesso";
                    return RedirectToAction(nameof(Index));

                }
                TempData["alertError"] = "Erro na model, tente novamente";
                return View();
            }
            catch(Exception ex)
            {
                TempData["alertError"] = ex.Message;
                return View();
            }

        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var contato = _contatosService.FindById(id.Value);
            if (contato == null)
            {
                return NotFound();
            }
            return View(contato);
        }

        [HttpPost]
        public IActionResult Edit(Contato contato)
        {
            if (ModelState.IsValid)
            {
                _contatosService.Update(contato);
                return RedirectToAction(nameof(Index));
            }
            return View(contato);

        }

        public IActionResult Delet(int? id)
        {
            if (id == null)
            {
                throw new Exception("Id not provided");
            }
            var contato = _contatosService.FindById(id.Value);
            if (contato == null)
            {
                return NotFound();
            }

            return View(contato);

        }

        [HttpPost]
        public IActionResult Delet(Contato contato)
        {
            _contatosService.DeletContato(contato);
            return RedirectToAction(nameof(Index));
        }

    }
}

SistemaDeContatos/Views/Contatos/Create.cshtml
@model SistemaDeContatos.Models.Entities.Contato

@{
    ViewData["title"] = "Cadastrar novo contato";
}

<div class="text-center">
    <h1>@ViewData["title"]</h1>
</div>


@if (TempData["alertError"] != null)
{
    <div class="alert alert-danger" role="alert">
        <button type="button" class="btn btn-danger btn-close btn-sm close-alert" arial-label="Close"></button>
        @TempData["alertError"];
    </div>
}


<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" >
            <div class="form-group">
                <label for="Nome" class="control-label">Nome</label>
                <input class="form-control" asp-for="Nome"/>
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="Nome" class="control-label">Email</label>
                <input type="email" class="form-control" asp-for="Email" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="Nome" class="control-label">Celular</label>
                <input class="form-control" asp-for="Celular" />
                <span asp-validation-for="Celular" class="text-danger"></span>
            </div>
            <div class="form-group">
                    <button class="btn btn-success" type="submit">Cadastrar</button>
                <a asp-action="Index" asp-controller="Contatos" class="btn btn-danger" role="button">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

SistemaDeContatos/Views/Contatos/Delet.cshtml
@model SistemaDeContatos.Models.Entities.Contato;


@{
    ViewData["title"] = "Excluir Contato";
}
<div class="text-center">
    <h1>@ViewData["title"]</h1>
</div>


<div>
    <h2>Deseja Realmente Apagar este contato? </h2>
    <div class="row">
        <div class="col-md-4">
            <dl>
                <dt>@Html.DisplayNameFor(x => x.Nome)</dt>
                <dd>@Html.DisplayFor(x => x.Nome)</dd>
                <dt>@Html.DisplayNameFor(x => x.Email)</dt>
                <dd>@Html.DisplayFor(x => x.Email)</dd>
                <dt>@Html.DisplayNameFor(x => x.Celular)</dt>
                <dd>@Html.DisplayFor(x => x.Celular)</dd>
            </dl>
        </div>
        <div>
            <form asp-action="Delet">
                <input type="hidden" asp-for="Id" />
                <button type="submit" class="btn btn-danger">Exluir</button>
                <a role="button" class="btn btn-primary" asp-action="Index" asp-controller="Contatos">voltar</a>
            </form>
        </div>
    </div>
</div>

SistemaDeContatos/Views/Contatos/Edit.cshtml
@model SistemaDeContatos.Models.Entities.Contato;
@{
    ViewData["title"] = "Editar Contato";
}

<div class="justify-content-center">
    <h1 class="align-content-md-center">@ViewData["title"]</h1>
</div>


@if (TempData["alertError"] != null)
{
    <div class="alert alert-danger" role="alert">
        <button type="button" class="btn btn-danger btn-close btn-sm close-alert" arial-label="Close"></button>
        @TempData["alertError"];
    </div>
}


<div class="Row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-controller="Contatos">
            <input type="hidden" asp-for="Id"/>
            <div class="form-group">
                <label class="control-label" asp-for="Nome"></label>
                <input class="form-control" asp-for="Nome" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label">Email</label>
                <input type="email" class="form-control" asp-for="Email" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Celular" class="control-label">Celular</label>
                <input class="form-control" asp-for="Celular" />
                <span asp-validation-for="Celular" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button class="btn btn-success" type="submit">Editar</button>
            </div>
        </form>
        <a asp-action="Index" asp-controller="Contatos" class="btn btn-danger" role="button">Voltar</a>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

SistemaDeContatos/Views/Contatos/Index.cshtml
@model IEnumerable<SistemaDeContatos.Models.Entities.Contato>

@{
    ViewData["title"] = "Contatos";
}

<div class="text-center">
    <h1>@ViewData["title"]</h1>
</div>

@if (TempData["alertSucess"] != null)
{
    <div class="alert alert-success" role="alert">
        <button type="button" class="btn btn-danger btn-close btn-sm close-alert" arial-label="Close"></button>
        @TempData["alertSucess"];
    </div>
}

@if (TempData["alertError"] != null)
{
    <div class="alert alert-danger" role="alert">
        <button type="button" class="btn btn-danger btn-close btn-sm close-alert" arial-label="Close"></button>
        @TempData["alertError"];
    </div>
}

<a class="btn btn-success" asp-action="Create" asp-controller="Contatos">Cadastrar novo contato</a>






<br />

<div>
    <table class="table table-striped table-hover" id="table-contatos" width="100%">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(s => s.Nome)</th>
                <th>@Html.DisplayNameFor(s => s.Email)</th>
                <th>@Html.DisplayNameFor(s => s.Celular)</th>
                <th>  </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var contato in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => contato.Nome)</td>
                    <td>@Html.DisplayFor(modelItem => contato.Email)</td>
                    <td>@Html.DisplayFor(modelItem => contato.Celular)</td>
                    <td>
                        <a role="link" asp-action="Edit" asp-controller="Contatos" asp-route-id="@contato.Id">Editar</a>
                        <a role="link" asp-action="Delet" asp-controller="Contatos" asp-route-id="@contato.Id">Deletar</a>

                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>