SistemaDeContatos/Models/Entities/Usuario.cs
using SistemaDeContatos.Helper;
using SistemaDeContatos.Models.Enums;
using System.ComponentModel.DataAnnotations;
using System.Globalization;

namespace SistemaDeContatos.Models.Entities
{
    public class Usuario
    {
        public int Id { get; set; }

        [Required(ErrorMessage ="Digite um nome")]
        [StringLength(maximumLength: 50,MinimumLength =4, ErrorMessage ="O nome tem que ter pelo menos 4 caracteres")]
        public string Nome { get; set; }

        [Required(ErrorMessage ="Digite um login")]
        public string Login { get; set; }

        [Required(ErrorMessage ="Digite uma senha")]
        public string Senha { get; set; }
        [Required(ErrorMessage ="Digite um email")]
        [EmailAddress(ErrorMessage ="Digite um email válido")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required(ErrorMessage ="Escolha um perfil")]
        public PerfilEnum? Perfil { get; set; }

        public DateTime DataCriacao { get; set; }
        public DateTime? DataAtualizacao { get; set; }

        public List<Contato> contatos { get; set; } = new List<Contato>(); 


        public Usuario()
        {
                
        }
        public Usuario(string nome, string login, string email, string senha, PerfilEnum perfil, DateTime dataCriacao)
        {
            Nome = nome;
            Login = login;
            Email = email;
            Perfil = perfil;
            Senha = senha;
            DataCriacao = dataCriacao;

        }

        public bool ValidaSenha(string senha)
        {
            return Senha == senha.GerarHash();
        }

        public void SetSenha()
        {
            Senha = Senha.GerarHash();
        }

        public void SetNovaSenha(string novaSenha)
        {
            Senha = novaSenha.GerarHash();
        }

        public string GerarNovaSenha()
        {
            string novaSenha = Guid.NewGuid().ToString().Substring(0, 8);
            Senha = novaSenha.GerarHash();
            return novaSenha;
        }

    }
}

SistemaDeContatos/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaDeContatos.Filters;
using SistemaDeContatos.Models.Entities;
using SistemaDeContatos.Services;

namespace SistemaDeContatos.Controllers
{
    [PaginaParaUsuarioLogadoAdmin]
    public class UsuarioController : Controller
    {
        private readonly UsuarioService _usuarioService;

        public UsuarioController(UsuarioService usuarioService)
        {
            _usuarioService = usuarioService;
        }
        public IActionResult Index()
        {
            
           var usuarios = _usuarioService.FindAll();
            return View(usuarios);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                _usuarioService.AddUsuario(usuario);
                return RedirectToAction(nameof(Index));
            }
            return View(usuario);


        }

        public IActionResult Edit(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            var usuario = _usuarioService.FindById(id.Value);
            if(usuario == null)
            {
                return NotFound();
            }
          
            return View(usuario);
        }

        [HttpPost]
        public IActionResult Edit(UsuarioSemSenha usuarioSemSenha)
        {
            try
            {
                Usuario usuario = null;
                if (ModelState.IsValid)
                {
                    usuario = new Usuario()
                    {
                        Id = usuarioSemSenha.Id,
                        Login = usuarioSemSenha.Login,
                        Email = usuarioSemSenha.Email,
                        Nome = usuarioSemSenha.Nome,
                        Perfil = usuarioSemSenha.Perfil

                    };
                    _usuarioService.Update(usuario);
                    return RedirectToAction(nameof(Index));
                }
            }
            catch(Exception e)
            {
                throw new Exception(e.Message);
            }
            return View();




        }

        public IActionResult Delet(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }
           var usuario =  _usuarioService.FindById(id.Value);
            if(usuario == null)
            {
                return NotFound();
            }
            return View(usuario);
        }

        [HttpPost]
        public IActionResult Delet(Usuario usuario)
        {
            if(usuario == null)
            {
                return NotFound();
            }
            _usuarioService.DeletUsuario(usuario);
            return RedirectToAction(nameof(Index));
        }
    }
}

SistemaDeContatos/Views/Usuario/Create.cshtml
@using SistemaDeContatos.Models.Enums
@model SistemaDeContatos.Models.Entities.Usuario

@{
    ViewData["title"] = "Cadastrar novo Usuário";
}

<div class="justify-content-center">
    <h1 class="align-content-md-center">@ViewData["title"]</h1>
</div>


@if (TempData["alertError"] != null)
{
    <div class="alert alert-danger" role="alert">
        <button type="button" class="btn btn-danger btn-close btn-sm close-alert" arial-label="Close"></button>
        @TempData["alertError"];
    </div>
}


    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div class="form-group">
                    <label for="Nome" class="control-label">Digite o nome</label>
                    <input class="form-control" asp-for="Nome" />
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label for="Login" class="control-label">Digite o login</label>
                    <input class="form-control" asp-for="Login" />
                    <span asp-validation-for="Login" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label for="Email" class="control-label">Digite o email do usuário</label>
                    <input type="email" class="form-control" asp-for="Email" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label for="Senha" class="control-label">Informe a senha do usuário</label>
                    <input type="password" class="form-control" asp-for="Senha" />
                    <span asp-validation-for="Senha" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label for="Perfil" class="form-label">Perfil</label>
                    <select class="form-control" asp-for="Perfil">
                        <option value="">Selecione</option>
                        <option value="1">@PerfilEnum.Admin</option>
                        <option value="2">@PerfilEnum.Padrao</option>
                        
                    <span asp-validation-for="Perfil" class="text-danger"></span>
                    </select>
                
                </div>
                <br />
                <div class="form-group align-content-center">
                    <button class="btn btn-success" type="submit">Cadastrar</button>
                    <a asp-action="Index" asp-controller="Usuario" class="btn btn-danger" role="button">Voltar</a>
                </div>
            </form>
        </div>
    </div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

SistemaDeContatos/Views/Usuario/Delet.cshtml
@model SistemaDeContatos.Models.Entities.Usuario;


@{
    ViewData["title"] = "Excluir Usuario";
}
<div class="justify-content-center">
    <h1 class="align-content-md-center">@ViewData["title"]</h1>
</div>


<div>
    <h2>Deseja Realmente Apagar este contato? </h2>
    <div class="row">
        <div class="col-md-4">
            <dl>
                <dt>@Html.DisplayNameFor(x => x.Nome)</dt>
                <dd>@Html.DisplayFor(x => x.Nome)</dd>
                <dt>@Html.DisplayNameFor(x => x.Email)</dt>
                <dd>@Html.DisplayFor(x => x.Email)</dd>
                <dt>@Html.DisplayNameFor(x => x.Login)</dt>
                <dd>@Html.DisplayFor(x => x.Login)</dd>
            </dl>
        </div>
        <div>
            <form asp-action="Delet" asp-controller="Usuario">
                <input type="hidden" asp-for="Id" />
                <button type="submit" class="btn btn-danger">Exluir</button>
                <a role="button" class="btn btn-primary" asp-action="Index" asp-controller="Usuario">voltar</a>
            </form>
        </div>
    </div>
</div>

SistemaDeContatos/Views/Usuario/Edit.cshtml
@using SistemaDeContatos.Models.Enums
@model SistemaDeContatos.Models.Entities.Usuario

@{
    ViewData["title"] = "Editar Usuário";
}

<div class="justify-content-center">
    <h1 class="align-content-md-center">@ViewData["title"]</h1>
</div>

@if (TempData["alertError"] != null)
{
    <div class="alert alert-danger" role="alert">
        <button type="button" class="btn btn-danger btn-close btn-sm close-alert" arial-label="Close"></button>
        @TempData["alertError"];
    </div>
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <input type="hidden" asp-for="Id"/>
            <div class="form-group">
                <label for="Nome" class="control-label">Nome</label>
                <input class="form-control" asp-for="Nome" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="Login" class="control-label">Login</label>
                <input class="form-control" asp-for="Login" />
                <span asp-validation-for="Login" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="Email" class="control-label">Email</label>
                <input type="email" class="form-control" asp-for="Email" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="Perfil" class="form-label">Perfil</label>
                <select class="form-control" asp-for="Perfil">
                    <option value="">Selecione</option>
                    <option value="1">@PerfilEnum.Admin</option>
                    <option value="2">@PerfilEnum.Padrao</option>
                    <span asp-validation-for="Perfil" class="text-danger"></span>
                </select>

            </div>
            <br />
            <div class="form-group align-content-center">
                <button class="btn btn-success" type="submit">Editar</button>
                <a asp-action="Index" asp-controller="Usuario" class="btn btn-danger" role="button">Voltar</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

SistemaDeContatos/Views/Usuario/Index.cshtml
@model IEnumerable<SistemaDeContatos.Models.Entities.Usuario>

@{
    ViewData["title"] = "Usuarios";
}



<a class="btn btn-success" asp-action="Create" asp-controller="Usuario">Cadastrar novo Usuario</a>

<br />
@if (TempData["alertSucess"] != null)
{
    <div class="alert alert-success" role="alert">
        <button type="button" class="btn btn-danger btn-close btn-sm close-alert" arial-label="Close"></button>
        @TempData["alertSucess"];
    </div>
}


@if (TempData["alertError"] != null)
{
    <div class="alert alert-danger" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close"></button>
        @TempData["alertError"];
    </div>
}

<br />

<div>
    <table class="table table-striped table-hover" id="table-usuarios" width="100%">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(s => s.Nome)</th>
                <th>@Html.DisplayNameFor(s => s.Login)</th>
                <th>@Html.DisplayNameFor(s => s.Email)</th>
                <th>@Html.DisplayNameFor(s => s.Perfil)</th>
                <th>@Html.DisplayNameFor(s => s.DataCriacao)</th>
                <th>@Html.DisplayNameFor(s => s.DataAtualizacao)</th>
                <th>  </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var usuario in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => usuario.Nome)</td>
                    <td>@Html.DisplayFor(modelItem => usuario.Login)</td>
                    <td>@Html.DisplayFor(modelItem => usuario.Email)</td>
                    <td>@(usuario.Perfil == SistemaDeContatos.Models.Enums.PerfilEnum.Admin? "Admin":"Padrão")</td>
                    <td>@Html.DisplayFor(modelItem => usuario.DataCriacao)</td>
                    <td>@Html.DisplayFor(modelItem => usuario.DataAtualizacao)</td>
                    <td>
                        <a role="link" asp-action="Edit" asp-controller="Usuario" asp-route-id="@usuario.Id">Editar</a>
                        <a role="link" asp-action="Delet" asp-controller="Usuario" asp-route-id="@usuario.Id">Deletar</a>

                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>